application: d--v--b
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets
  static_dir: assets

- url: /libs
  static_dir: libs

- url: /.*
  script: buzhidao.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest